version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-southeast-1:359170549571:task-definition/sample-task-definition:2"
        LoadBalancerInfo:
          ContainerName: "samplecontainer"
          ContainerPort: 80
